### ISSUE TITLE
Show recent submissions in an activity feed

### ISSUE THREAD

**Issue by emwalker** [emwalker/digraph#16]
From Jonathan:

> I’d also like to see a feed of changes on the home page, “joe added taco recipes + 6 child topics”, timestamps optional to obfuscate staleness (if the site doesn’t see updates for days at a time) 

I was thinking of doing something kind of similar, except not aggregating the feed as much, more along the lines of a history of edits to an article in Wikipedia:
* So-and-so added ["Claims of Shoddy Production Draw Scrutiny to a Second Boeing Jet"](https://www.nytimes.com/2019/04/20/business/boeing-dreamliner-production-problems.html) and tagged it with [Lion Air Flight 610, Ethiopian Airlines Flight 302 and the Boeing 737 MAX](https://digraph.app/wiki/topics/c285ce08-19c8-4225-8705-06510a6199e5)
* Another-person added ...

**Comment by emwalker** [comment]
The question of where the activity feed goes is an interesting one.  I was thinking of putting it behind a "Recent" link in the header.  The front page perhaps one day?

**Comment by emwalker** [comment]
Closing, as the new "Recent activity" feed is a first pass, and issues can be filed for later bugs and enhancements.

**Comment by tensiondriven** [comment]
Putting a little bit of it on the home page is a good way to communicate to the user what the site is for, as it will say "Person X did Y"... I think of it as more of a marketing/communications/discoverability feature than a productivity feature

**Comment by emwalker** [comment]
Would it replace the chart, with the chart being moved off to another page?

**Comment by tensiondriven** [comment]
My thought is that it would go toward the bottom, maybe below or close to the fold, keeping the graph.
—
Sent from my Battlestation

Jonathan Yankovich – Helping people work better together
» Subscribe to my YouTube channel <https://www.youtube.com/channel/UCvrSgbiLll8wMLu43SYYPkA>
» See my Roles at HolacracyOne <https://app.glassfrog.com/org/5/people/24697>

**Comment by emwalker** [comment]
@tensiondriven I decided to put a little more effort into the landing page, just so that it's not a distraction. Let me know what you think.
