### ISSUE TITLE
Usability issue: Can't search from home page

### ISSUE THREAD

**Issue by tensiondriven** [emwalker/digraph#18]
As a user, I want to be able to add a link quickly.

I came to digraph.app to add a link, and got confused because the search box was gone.   If there was a search box on the home page I could have used it to find the topic I needed to add my link.  Instead of was forced to read text and click on something.

**Comment by emwalker** [comment]
@tensiondriven I didn't see this until now.  Is this still something of interest?  One question I have here is what should be on the homepage?
- Something like what is there now
- A marketing landing page, with the actual app that you work with on another domain like `en.digraph.app`
- A usable page of the app hosted on the bare domain

**Comment by tensiondriven** [comment]
My vote is for the third option (usable page), or at least a portion of the page which
1) displays some recent additions or other information that give people a flavor for what the product is about and 
2) An easy way to add new content for people who only use it every few weeks

if the current visualization hilighted recent additions, or even randomly picked one and made its "path" bold, that would be more interesting.  As it is, its doesn't convey much information, even after having seen it grow over time.

My main thing as a user is that I want to be able to go to the site, drop a link, and move on.  So, I'd like to be able to do that from the sidebar.

**Comment by emwalker** [comment]
@tensiondriven I've added some stuff along the lines of your request.  When adding new content, the user will usually want to start with a search (at the present time, anyway), so I've added a search box.

**Comment by emwalker** [comment]
@tensiondriven some feedback on the new landing page: https://www.indiehackers.com/product/digraph/-LlOh6D11RtQCuVLEeYP.
